---
title: "coverage_plot_ggplot_never_v_common"
output: html_document
---

```{r}
library(data.table)
library(ggplot2)
library(RColorBrewer)
library(ggpubr)
source("https://raw.githubusercontent.com/datavizpyr/data/master/half_flat_violinplot.R")
library(ggforce)
#library(scales)

```

```{r}

df <- data.frame(fread('guy11_fungap_out_12_28_20.bed'))

df_splitreads <- data.frame(fread('G3.normalized.splitreadspergene'))

colnames(df) <- c('CHROMOSOME', 'start', 'end', 'gene')

df$CHROMOSOME <- as.numeric(substring(df$CHROMOSOME, 11, 12))
                          
df$middle <- df$start + (df$end - df$start) * 0.5

df$splitreads <- df_splitreads$V2

df$status <- NA

df$status[df$splitreads == 0] <- 'eccDNA-absent'


n_common_genes <- floor(length(df$splitreads[df$splitreads != 0])/10)

common_genes_cutoff <- sort(df$splitreads, decreasing=TRUE)[n_common_genes]

df$status[df$splitreads >= common_genes_cutoff] <- 'eccDNA-associated'

df$status[is.na(df$status)] <- 'Other genes'

df

```

```{r}

df_chromsizes <- data.frame(fread('guy11_genome_baoetal2017.chromsizes'))

colnames(df_chromsizes) <- c('chrom', 'size')
df_chromsizes$chrom <- as.numeric(substring(df_chromsizes$chrom, 11, 12))


v <- numeric()

for (scaffold in 1:56){
  v[scaffold] <- df_chromsizes$size[df_chromsizes$chrom == scaffold]
}

x <- numeric()

for (scaffold in 1:56){
  x[scaffold] <- sum(v[1:scaffold]) - v[scaffold]
}


f <- function(g) {
 base <- as.numeric(g[5])
 scaffold <- as.numeric(g[1])
 base_total <- base + x[scaffold]
 return(base_total)
}

df$BASE_TOTAL <- apply(df, 1, f)

df$status <- factor(df$status, levels=c('eccDNA-absent', 'Other genes', 'eccDNA-associated'))


```

```{r}

start_subset <- 1

end_subset <- 5

end_subset_first_few <- 5

count <- end_subset - start_subset + 1

ticks <- numeric()

for (scaffold in start_subset:end_subset){
  ticks <- c(ticks, v[scaffold]*0.5 + (sum(v[start_subset:scaffold]) - v[scaffold]))
  ticks <- c(ticks, v[scaffold]*1 + (sum(v[start_subset:scaffold]) - v[scaffold]))
}

labs <- rep(start_subset:end_subset, each=2)

df_subset <- df[df$CHROMOSOME >= start_subset & df$CHROMOSOME <= end_subset,]

p1 <- ggplot() + 
  geom_point(data = df_subset[df_subset$status=="Other genes",], aes(x=BASE_TOTAL, y=splitreads), color='grey',size=0.1)+
  geom_point(data = df_subset[df_subset$status=="eccDNA-absent",], aes(x=BASE_TOTAL, y=splitreads), color='#03254c',size=0.1) +
  geom_point(data = df_subset[df_subset$status=="eccDNA-associated",], aes(x=BASE_TOTAL, y=splitreads), color='#E6AB02',size=0.1) +
  geom_segment(aes(x=0, xend=Inf, y=common_genes_cutoff, yend=common_genes_cutoff ),colour='#E6AB02')+
  scale_x_continuous(labels=labs, breaks = ticks,
                     limits = c((sum(v[1:start_subset]) - v[start_subset]),
                           sum(v[1:start_subset]) - v[start_subset] + sum(v[1:end_subset_first_few]))) + 
  theme_classic() + xlab('Scaffold') +
  ylim(0, max(df$splitreads)) +
  theme(axis.text.x = element_text(colour=c(rep(c('black','transparent'),count))))+
  theme(axis.ticks.x = element_line(colour=c(rep(c('transparent','black'),count))))+
  ylab('Normalized encompassing \nsplit read count')+
  theme(axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_blank(), legend.position = 'bottom', legend.text=element_text(size=6)) + guides(colour = guide_legend(override.aes = list(size=2)))

# should be 5000 for high res
ggsave('test.tiff', plot=p1, width=6.5, height=1.75, device = 'tiff', dpi = 1000)

```

```{r}

start_subset <- 6

end_subset <- 56

count <- end_subset - start_subset + 1

ticks <- numeric()

for (scaffold in start_subset:end_subset){
  if (scaffold <= 15) {
    ticks <- c(ticks, v[scaffold]*0.5 + (sum(v[start_subset:scaffold]) - v[scaffold]))
    } else if (scaffold == 20) {
      ticks <- c(ticks, v[scaffold]*0.5 + (sum(v[start_subset:scaffold]) - v[scaffold]))
    } 
  ticks <- c(ticks, v[scaffold]*1 + (sum(v[start_subset:scaffold]) - v[scaffold]))
}

ticks <- ticks + sum(v[1:end_subset_first_few])

labs <- character()

for (scaffold in start_subset:end_subset){
  if (scaffold <= 15) {
    labs <- c(labs, scaffold)
    } else if (scaffold == 20) {
      labs <- c(labs,scaffold)
    } 
  labs <- c(labs, scaffold)
}

#tick colors

tick_colors <- character()
label_colors <- character()

for (scaffold in start_subset:end_subset){
  if (scaffold <= 15) {
    tick_colors <- c(tick_colors, 'transparent', 'black')
    } else if (scaffold == 20) {
      tick_colors <- c(tick_colors, 'transparent', 'black')
    } else {
      tick_colors <- c(tick_colors, 'black')
    }
  if (scaffold <= 15) {
    label_colors <- c(label_colors, 'black', 'transparent')
    } else if (scaffold == 20) {
      label_colors <- c(label_colors, 'black', 'transparent')
    } else {
      label_colors <- c(label_colors, 'transparent')
    }
}



df_subset <- df[df$CHROMOSOME >= start_subset & df$CHROMOSOME <= end_subset,]

p2 <- ggplot() + 
  geom_point(data = df_subset, aes(x=BASE_TOTAL, y=splitreads,color=status), size=0.1)+
  scale_color_manual(values=c('#03254c', "grey", "#E6AB02"))+
  scale_x_continuous(labels=labs, breaks = ticks,
                     limits = c((sum(v[1:start_subset]) - v[start_subset]),
                           sum(v[1:start_subset]) - v[start_subset] + sum(v[1:end_subset_first_few]))) + 
  theme_classic() + xlab('Scaffold') +
  ylim(0, max(df$splitreads)) +
  theme(axis.text.x = element_text(colour=label_colors))+
  theme(axis.ticks.x = element_line(colour=tick_colors))+
  ylab('Normalized junction \nsplit read count')+
  theme(axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_blank(), legend.position = 'bottom', legend.text=element_text(size=6))+ guides(colour = guide_legend(override.aes = list(size=2)))

# should be 5000 for high res
ggsave('test2.tiff', plot=p2, width=6.5, height=1, device = 'tiff', dpi = 1000)

```

```{r}
both <- ggarrange(p1,p2, ncol=1, nrow=2, common.legend = TRUE, legend='bottom')

ggsave('test3.tiff', plot=both, width=6.5, height=2, device = 'tiff', dpi = 1000)

ggsave('test3.pdf', plot=both, width=6.5, height=3.5, device = 'pdf')

```
















