---
title: "ltr_profile_plots"
output: html_document
---

```{r}

library(data.table)
library(ggplot2)

te_list <- list()

te_list[[1]] <- c('copia1', 'Copia1\n ', 539, 6562,"#E6AB02")
te_list[[2]] <- c('MAGGY', 'MAGGY\n ', 255, 5134,"#7570B3")
te_list[[3]] <- c('GYMAG1', 'GYMAG1\n ', 210, 5680,'#03254c')
te_list[[4]] <- c('GYMAG2', 'GYMAG2\n ', 195, 5483,"#2a9df4")
te_list[[5]] <- c('MGRL3', 'MGRL3\n ', 215, 5880,"#E7298A")
te_list[[6]] <- c('PYRET', 'PYRET\n ', 462, 6491,"#66A61E")


```



```{r}


for (te in te_list) {
  
element <- te[[1]]
element_label <- te[[2]]
te_ltr_length <- as.numeric(te[[3]])
te_internal_length <- as.numeric(te[[4]])
te_color <- te[[5]]
  
df_read <- t(data.frame(fread(paste(element,".readcoverage.normalized_and_average..tab", sep=''))))

df <- data.frame( bin=as.vector(df_read[3:nrow(df_read),1]),
                  val=c(df_read[3:nrow(df_read),2]),
                  label=c(rep('coverage',300)))

df$bin <- as.numeric(as.character(df$bin))
df$val <- as.numeric(as.character(df$val))

te_total_length <- te_ltr_length + te_ltr_length + te_internal_length

ltr_one_start <- 100
ltr_one_end <- (te_ltr_length/te_total_length * 100) + 100
ltr_one_middle <- ltr_one_start + ((ltr_one_end-ltr_one_start)/2)
ltr_two_start <- 200 - (te_ltr_length/te_total_length * 100)
ltr_two_end <- 200
ltr_two_middle <- ltr_two_start + ((ltr_two_end-ltr_two_start)/2)


p <- ggplot(df, aes(x=bin, y=val)) + geom_line(color=te_color, lwd=0.5) + theme_classic() +
  scale_x_continuous(labels=c('-0.3kb', '', 'LTR', '', '', 'LTR', '', '0.3kb'), 
                     breaks=c(70,ltr_one_start, ltr_one_middle, ltr_one_end, ltr_two_start, ltr_two_middle, ltr_two_end,230),
                     limits = c(70,230)) + 
  theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_blank(), legend.text=element_text(size=8)) +
  theme(axis.ticks.x = element_line(colour=c('black', 'black', 'transparent', 'black', 'black',
                                             'transparent', 'black', 'black'))) +
  ylab('Normalized read coverage') + xlab(element_label)

ggsave(paste(element,'_plot_profile.pdf',sep=''), plot=p, width=(6.5/3), height=2)

}

```

