---
title: "if_expression_large_eccdnas_analysis"
output: html_document
---


```{r}

library(data.table)
library(ggplot2)
library(scales)

df_rpkm <- data.frame(fread('G3.RPKMvsSRs'))

colnames(df_rpkm) <- c("gene", "rpkm", "srs")

df_rpkm <- df_rpkm[df_rpkm$srs != 0 & df_rpkm$rpkm != 0,]

df_rpkm$rpkm <- log10(df_rpkm$rpkm)

df_rpkm$srs <- log10(df_rpkm$srs)

cor_test <- cor.test(df_rpkm$rpkm, df_rpkm$srs, method=c("pearson"))
cor <-  round(cor_test$estimate[[1]], digits = 4)
pvalue <- round(cor_test$p.value[[1]], digits = 4)

p <- ggplot(df_rpkm, aes(x=rpkm, y=srs)) +
    stat_density_2d(aes(fill = ..level..), geom = "polygon") +
    labs(x="Log 10 RPKM", y="Log 10 junction split \nreads per gene") + theme_classic() +
    labs(fill = "Gene density")+
    geom_smooth(method='lm', color='red')+
    labs(title=paste("Pearson's correlation = ", cor, ", p-value = ", pvalue, sep=''))+
    theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_text(size=8), legend.text=element_text(size=6), 
          plot.title=element_text(size=8, hjust=0.5))


p

ggsave("if_expression_large_eccdnas_rpkm_plot.pdf", plot = p, width = 6.5, height = 3)

```

```{r}

df_rpkm$rank_rpkm <- rank(df_rpkm$rpkm)
df_rpkm$rank_srs <- rank(df_rpkm$srs)

cor_test <- cor.test(df_rpkm$rpkm, df_rpkm$srs, method=c("spearman"))
cor <-  round(cor_test$estimate[[1]], digits = 4)


p <- ggplot(df_rpkm, aes(x=rank_rpkm, y=rank_srs)) +
    stat_density_2d(aes(fill = ..level..), geom = "polygon") +
    labs(x="Rank RPKM", y="Rank junction split \nreads per gene") + theme_classic() +
    labs(fill = "Gene density")+
    geom_abline(intercept=0, slope=1, linetype=3)+
    labs(title=paste("Spearman's rank correlation = ", cor, sep=''))+
    theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_text(size=8), legend.text=element_text(size=6), 
          plot.title=element_text(size=8, hjust=0.5))


p

ggsave("if_expression_large_eccdnas_rpkm_rank_plot.pdf", plot = p, width = 6.5, height = 3)

```


```{r}
cor.test(df_rpkm$rpkm, df_rpkm$srs, method=c("spearman"))
```

```{r}
summary(lm(df_rpkm$srs ~ df_rpkm$rpkm))
```

```{r}
par(mfrow=c(2,2))
plot(lm(df_rpkm$srs ~ df_rpkm$rpkm))

pdf(file = "if_expression_large_eccdnas_rpkm_diagnostics.pdf", width = 6, height = 4)
par(mfrow=c(2,2))
plot(lm(df_rpkm$srs ~ df_rpkm$rpkm))
dev.off()
```