---
title: "ltr_splitreads_correlation"
output: html_document
---

```{r}
library(data.table)
library(ggplot2)
library(scales)

df <- data.frame(fread('ltr_sr_and_read_cov_and_junction_sr_perfeature_normalized'))

colnames(df) <- c("feature", "ltr_srs", 'sd', "feature2", "reads", 'sd2', "feature3", "eccs", 'sd3')

# df <- df[df$srs<50,]

df

#df_rpkm <- df_rpkm[df_rpkm$srs != 0 & df_rpkm$rpkm != 0,]

#df_rpkm$rpkm <- log10(df_rpkm$rpkm)

#df_rpkm$srs <- log10(df_rpkm$srs)

p <- ggplot(df, aes(x=reads, y=ltr_srs)) + geom_smooth(method='lm', color='red') + geom_point()

p

#+
#    stat_density_2d(aes(fill = ..level..), geom = "polygon") +
#    labs(x="Log10 RPKM", y="Log10 junction split \nreads per gene") + theme_classic() + 
#    labs(fill = "Gene density")+
#    theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_text(size=8), legend.text=element_text(size=6))


ggsave("ct_expression_large_eccdnas_rpkm_plot.pdf", plot = p, width = 6.5, height = 3)
```

```{r}

element <- "MGRL3"
  
segment <- ""

cor1 <- 'reads'

cor2 <- 'ltr_srs'


df_test <- df[grepl(element, df$feature),]

df_test <- df_test[grepl(segment, df_test$feature),]

p <- ggplot(df_test, aes_string(x=cor1, y=cor2)) + geom_smooth(method='lm', color='red') + geom_point()

p

cor.test(df_test[[cor1]], df_test[[cor2]], method=c("pearson"))

summary(lm(df_test[[cor2]] ~ df_test[[cor1]]))

```



```{r}
cor.test(df_gymag1$ltr_srs, df_gymag1$reads, method=c("pearson"))

```

```{r}

element <- "copia1"
  
segment <- "INTERNAL"

df_test <- df[grepl(element, df$feature),]

df_test <- df_test[grepl(segment, df_test$feature),]

p <- ggplot(df_test, aes(x=log(reads), y=log(eccs))) + geom_smooth(method='lm', color='red') + geom_point()

p

cor.test(df_test$ltr_srs, df_test$reads, method=c("pearson"))

summary(lm(df_test$reads ~ df_test$ltr_srs))


```

